In [6]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import networks as nw

In [7]:
data_url = "charrette.csv"
df = pd.read_csv(data_url)
df.head()

   fig_id fig_type  character     pos
0     354       CH  CRESTIIEN  PROPER
1     373       CH        KEU  PROPER
2     373       CH        KEU  PROPER
3     374       CH        KEU  PROPER
4     377       CH        KEU  PROPER

In [8]:
node_cols = ['fig_type','character']
df[node_cols].head()

  fig_type  character
0       CH  CRESTIIEN
1       CH        KEU
2       CH        KEU
3       CH        KEU
4       CH        KEU

In [4]:
nw.tidy_to_graph
nw.graph_to_igraph
graphplot

NameError: name 'graphplot' is not defined

In [9]:
N, E = nw.tidy_to_graph(df, node_cols)
G = nw.graph_to_igraph(N, E)
nw.graphplot(G, layout_types = 'rt_circular')

TypeError: graphplot() got an unexpected keyword argument 'layout_types'. Did you mean 'layout_type'?