# Week 2 Challenge 1

DS 2023 | Communicating with Data

## Overview

In today's challenge, you will apply what you have learned about the columns in a tidy table with voting results for the 2013 Montreal mayoral election.

Work in groups to answer these questions.

When finished, submit to today's participation assignment.

## Set Up

We import Pandas and the data set from Plotly.

We will go into more detail about using Pandas in subsequent lessons.

In [1]:
import pandas as pd
from plotly.express import data as pxdata

election = pxdata.election()
election.head()

,district,Coderre,Bergeron,Joly,total,winner,result,district_id
0,101-Bois-de-Liesse,2481,1829,3024,7334,Joly,plurality,101
1,102-Cap-Saint-Jacques,2525,1163,2675,6363,Joly,plurality,102
2,11-Sault-au-Récollet,3348,2770,2532,8650,Coderre,plurality,11
3,111-Mile-End,1734,4782,2514,9030,Bergeron,majority,111
4,112-DeLorimier,1770,5933,3044,10747,Bergeron,majority,112

## Questions

### 1. What is the unit of observation?

Answer: election winner in each montreal district in 2013

### 2. Classify the columns by their use: identification, grouping, and measurement

Create three lists: `ids`, `groupers`, and `measures`. 

Populate each with a list of the appropriate column names.

> [!tip] The lists are initialized for you below. Just cut-and-paste the columns names into them.

In [2]:
election.columns

Index(['district', 'Coderre', 'Bergeron', 'Joly', 'total', 'winner', 'result',
       'district_id'],
      dtype='str')

Identiders

In [6]:
ids = ['district','district_id']

Groupers

In [7]:
groupers = ['winner','result']

Measurements

In [8]:
measures = ['Coderre','Bergeron','Joly']

### 3. Reorder the columns with identifiers first, groupers seconds, and measurements third.

Use the lists to order the columns. 

Hint: Pass your lists to the dataframes' selector (i.e. `measurements[]`.

```python
measurements[ids + groupers + measures]
```

### Submit

Submit a URL to this document as your participation for today.

In [21]:
candidates = ['Coderre', 'Bergeron', 'Joly']

In [24]:
election1 = election.set_index('district_id')[candidates]
election1

             Coderre  Bergeron  Joly
district_id
101             2481      1829  3024
102             2525      1163  2675
11              3348      2770  2532
111             1734      4782  2514
112             1770      5933  3044
113             1455      3599  2316
12              3252      2521  2543
121             5456      1760  3330
122             4734      1879  2852
123             5737       958  1656
13              2979      3430  2873
131             1827      6408  2815
132             2331      5748  2788
133             2670      4962  3234
134             3673      3155  2431
14              3612      1554  2081
141             4308      1320  3959
142             4104      1459  2822
151             3931       882  1641
152             5387      1184  1908
161             2432      3368  3578
162             2566      2092  2438
171             3347      2562  3291
172             2476      2631  2849
181             1451       754  1894
182             1906      2169  2282
183             1347      2827  2271
191             3668       984  1220
192             2878      2666  2039
193             2201      5819  2782
194             2420      1793  1402
21              2184       691  1076
22              1589       708  1172
23              2526       851  1286
31              1873      1182  1232
32              1644      1950  1578
33              1548      1503  1636
34              1773      2653  3262
35              2040      1437  2648
41              1165       832  1266
42              1193       653  1157
43              1325      1205  1908
51              4201      1642  3717
52              3536      1330  2943
61               631       258   998
62               595       226  1068
63               518       224   690
64               332       131   326
71              3694      2589  3454
72              2746      3250  3139
73              1546      3679  2675
74              3509      2178  2338
81              6591      1085  1435
82              6229       780  1051
91               996       643   423
92               540       833   592
93               446       465   419
94               491       698   489

In [29]:
pd.concat([election1[candidate] for candidate in candidates], keys=candidates).to_frame()

                        0
        district_id
Coderre 101          2481
        102          2525
        11           3348
        111          1734
        112          1770
...                   ...
Joly    82           1051
        91            423
        92            592
        93            419
        94            489

[174 rows x 1 columns]